const cityData = {
  sunSetTime: 19,
  sunRiseTime: 5,
  currentHour: 15,
  locationInfo: {
    full: 'Tucson, AZ',
    city: 'Tucson',
    state: 'AZ',
    state_name: 'Arizona',
    country: 'US',
    country_iso3166: 'US',
    zip: '85701',
    magic: '1',
    wmo: '99999',
    latitude: '32.22000122',
    longitude: '-110.97000122',
    elevation: '728.2',
  },
  curTemp: 102,
  condition: 'Clear',
  icon: 'clear',
  lastUpdateTime: 'Last Updated on June 5, 3:48 PM MST',
  highTemp: '102',
  lowTemp: '75',
  date: {
    epoch: '1496714400',
    pretty: '7:00 PM MST on June 05, 2017',
    day: 5,
    month: 6,
    year: 2017,
    yday: 155,
    hour: 19,
    min: '00',
    sec: 0,
    isdst: '0',
    monthname: 'June',
    monthname_short: 'Jun',
    weekday_short: 'Mon',
    weekday: 'Monday',
    ampm: 'PM',
    tz_short: 'MST',
    tz_long: 'America/Phoenix',
  },
  forecastDisc: 'Clear. Lows overnight in the mid 70s.',
  sevenHourData: [
    {
      temp: '104',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 PM',
      hour: 16,
    },
    {
      temp: '103',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 PM',
      hour: 17,
    },
    {
      temp: '102',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 PM',
      hour: 18,
    },
    {
      temp: '100',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
    },
    {
      temp: '95',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
    },
    {
      temp: '92',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
    },
    {
      temp: '90',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
    },
  ],
  tenDayData: [
    {
      day: 5,
      month: 'Jun',
      dayName: 'Monday',
      condition: 'Clear',
      icon: 'clear',
      highTemp: '102',
      lowTemp: '75',
    },
    {
      day: 6,
      month: 'Jun',
      dayName: 'Tuesday',
      condition: 'Clear',
      icon: 'clear',
      highTemp: '104',
      lowTemp: '75',
    },
    {
      day: 7,
      month: 'Jun',
      dayName: 'Wednesday',
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      highTemp: '103',
      lowTemp: '73',
    },
    {
      day: 8,
      month: 'Jun',
      dayName: 'Thursday',
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      highTemp: '102',
      lowTemp: '72',
    },
    {
      day: 9,
      month: 'Jun',
      dayName: 'Friday',
      condition: 'Clear',
      icon: 'clear',
      highTemp: '103',
      lowTemp: '69',
    },
    {
      day: 10,
      month: 'Jun',
      dayName: 'Saturday',
      condition: 'Clear',
      icon: 'clear',
      highTemp: '101',
      lowTemp: '70',
    },
    {
      day: 11,
      month: 'Jun',
      dayName: 'Sunday',
      condition: 'Clear',
      icon: 'clear',
      highTemp: '99',
      lowTemp: '68',
    },
    {
      day: 12,
      month: 'Jun',
      dayName: 'Monday',
      condition: 'Clear',
      icon: 'clear',
      highTemp: '98',
      lowTemp: '68',
    },
    {
      day: 13,
      month: 'Jun',
      dayName: 'Tuesday',
      condition: 'Clear',
      icon: 'clear',
      highTemp: '101',
      lowTemp: '69',
    },
    {
      day: 14,
      month: 'Jun',
      dayName: 'Wednesday',
      condition: 'Clear',
      icon: 'clear',
      highTemp: '104',
      lowTemp: '71',
    },
  ],
  twentyFourData: [
    {
      temp: '104',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 PM',
      hour: 16,
      day: 5,
    },
    {
      temp: '103',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 PM',
      hour: 17,
      day: 5,
    },
    {
      temp: '102',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 PM',
      hour: 18,
      day: 5,
    },
    {
      temp: '100',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 5,
    },
    {
      temp: '95',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 5,
    },
    {
      temp: '92',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 5,
    },
    {
      temp: '90',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 5,
    },
    {
      temp: '87',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 5,
    },
    {
      temp: '84',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 6,
    },
    {
      temp: '82',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 6,
    },
    {
      temp: '80',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 6,
    },
    {
      temp: '78',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 6,
    },
    {
      temp: '77',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 6,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 6,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 AM',
      hour: 6,
      day: 6,
    },
    {
      temp: '80',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '7:00 AM',
      hour: 7,
      day: 6,
    },
    {
      temp: '84',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 AM',
      hour: 8,
      day: 6,
    },
    {
      temp: '89',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 AM',
      hour: 9,
      day: 6,
    },
    {
      temp: '92',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 AM',
      hour: 10,
      day: 6,
    },
    {
      temp: '95',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 AM',
      hour: 11,
      day: 6,
    },
    {
      temp: '98',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 PM',
      hour: 12,
      day: 6,
    },
    {
      temp: '100',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '1:00 PM',
      hour: 13,
      day: 6,
    },
    {
      temp: '102',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '2:00 PM',
      hour: 14,
      day: 6,
    },
    {
      temp: '102',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '3:00 PM',
      hour: 15,
      day: 6,
    },
    {
      temp: '103',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '4:00 PM',
      hour: 16,
      day: 6,
    },
    {
      temp: '102',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '5:00 PM',
      hour: 17,
      day: 6,
    },
    {
      temp: '101',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '6:00 PM',
      hour: 18,
      day: 6,
    },
    {
      temp: '99',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '7:00 PM',
      hour: 19,
      day: 6,
    },
    {
      temp: '96',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '8:00 PM',
      hour: 20,
      day: 6,
    },
    {
      temp: '92',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '9:00 PM',
      hour: 21,
      day: 6,
    },
    {
      temp: '89',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '10:00 PM',
      hour: 22,
      day: 6,
    },
    {
      temp: '87',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '11:00 PM',
      hour: 23,
      day: 6,
    },
    {
      temp: '85',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '12:00 AM',
      hour: 0,
      day: 7,
    },
    {
      temp: '82',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '1:00 AM',
      hour: 1,
      day: 7,
    },
    {
      temp: '80',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '2:00 AM',
      hour: 2,
      day: 7,
    },
    {
      temp: '79',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '3:00 AM',
      hour: 3,
      day: 7,
    },
    {
      temp: '78',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '4:00 AM',
      hour: 4,
      day: 7,
    },
    {
      temp: '76',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '5:00 AM',
      hour: 5,
      day: 7,
    },
    {
      temp: '77',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '6:00 AM',
      hour: 6,
      day: 7,
    },
    {
      temp: '81',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '7:00 AM',
      hour: 7,
      day: 7,
    },
    {
      temp: '85',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '8:00 AM',
      hour: 8,
      day: 7,
    },
    {
      temp: '89',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '9:00 AM',
      hour: 9,
      day: 7,
    },
    {
      temp: '92',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '10:00 AM',
      hour: 10,
      day: 7,
    },
    {
      temp: '95',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '11:00 AM',
      hour: 11,
      day: 7,
    },
    {
      temp: '98',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '12:00 PM',
      hour: 12,
      day: 7,
    },
    {
      temp: '100',
      icon: 'mostlycloudy',
      condition: 'Mostly Cloudy',
      time: '1:00 PM',
      hour: 13,
      day: 7,
    },
    {
      temp: '101',
      icon: 'mostlycloudy',
      condition: 'Mostly Cloudy',
      time: '2:00 PM',
      hour: 14,
      day: 7,
    },
    {
      temp: '101',
      icon: 'mostlycloudy',
      condition: 'Mostly Cloudy',
      time: '3:00 PM',
      hour: 15,
      day: 7,
    },
    {
      temp: '100',
      icon: 'mostlycloudy',
      condition: 'Mostly Cloudy',
      time: '4:00 PM',
      hour: 16,
      day: 7,
    },
    {
      temp: '99',
      icon: 'mostlycloudy',
      condition: 'Mostly Cloudy',
      time: '5:00 PM',
      hour: 17,
      day: 7,
    },
    {
      temp: '98',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '6:00 PM',
      hour: 18,
      day: 7,
    },
    {
      temp: '96',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 7,
    },
    {
      temp: '93',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 7,
    },
    {
      temp: '90',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 7,
    },
    {
      temp: '87',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 7,
    },
    {
      temp: '85',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 7,
    },
    {
      temp: '82',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 8,
    },
    {
      temp: '80',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 8,
    },
    {
      temp: '78',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 8,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 8,
    },
    {
      temp: '75',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 8,
    },
    {
      temp: '74',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 8,
    },
    {
      temp: '74',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '6:00 AM',
      hour: 6,
      day: 8,
    },
    {
      temp: '80',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '7:00 AM',
      hour: 7,
      day: 8,
    },
    {
      temp: '86',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '8:00 AM',
      hour: 8,
      day: 8,
    },
    {
      temp: '90',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '9:00 AM',
      hour: 9,
      day: 8,
    },
    {
      temp: '93',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '10:00 AM',
      hour: 10,
      day: 8,
    },
    {
      temp: '95',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '11:00 AM',
      hour: 11,
      day: 8,
    },
    {
      temp: '98',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '12:00 PM',
      hour: 12,
      day: 8,
    },
    {
      temp: '99',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '1:00 PM',
      hour: 13,
      day: 8,
    },
    {
      temp: '100',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '2:00 PM',
      hour: 14,
      day: 8,
    },
    {
      temp: '101',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '3:00 PM',
      hour: 15,
      day: 8,
    },
    {
      temp: '101',
      icon: 'mostlycloudy',
      condition: 'Mostly Cloudy',
      time: '4:00 PM',
      hour: 16,
      day: 8,
    },
    {
      temp: '100',
      icon: 'mostlycloudy',
      condition: 'Mostly Cloudy',
      time: '5:00 PM',
      hour: 17,
      day: 8,
    },
    {
      temp: '99',
      icon: 'partlycloudy',
      condition: 'Partly Cloudy',
      time: '6:00 PM',
      hour: 18,
      day: 8,
    },
    {
      temp: '96',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 8,
    },
    {
      temp: '93',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 8,
    },
    {
      temp: '90',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 8,
    },
    {
      temp: '87',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 8,
    },
    {
      temp: '85',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 8,
    },
    {
      temp: '82',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 9,
    },
    {
      temp: '80',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 9,
    },
    {
      temp: '78',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 9,
    },
    {
      temp: '75',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 9,
    },
    {
      temp: '74',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 9,
    },
    {
      temp: '73',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 9,
    },
    {
      temp: '73',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 AM',
      hour: 6,
      day: 9,
    },
    {
      temp: '79',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 AM',
      hour: 7,
      day: 9,
    },
    {
      temp: '84',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 AM',
      hour: 8,
      day: 9,
    },
    {
      temp: '89',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 AM',
      hour: 9,
      day: 9,
    },
    {
      temp: '92',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 AM',
      hour: 10,
      day: 9,
    },
    {
      temp: '94',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 AM',
      hour: 11,
      day: 9,
    },
    {
      temp: '97',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 PM',
      hour: 12,
      day: 9,
    },
    {
      temp: '99',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 PM',
      hour: 13,
      day: 9,
    },
    {
      temp: '100',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 PM',
      hour: 14,
      day: 9,
    },
    {
      temp: '101',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 PM',
      hour: 15,
      day: 9,
    },
    {
      temp: '101',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 PM',
      hour: 16,
      day: 9,
    },
    {
      temp: '100',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 PM',
      hour: 17,
      day: 9,
    },
    {
      temp: '99',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 PM',
      hour: 18,
      day: 9,
    },
    {
      temp: '96',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 9,
    },
    {
      temp: '91',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 9,
    },
    {
      temp: '88',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 9,
    },
    {
      temp: '85',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 9,
    },
    {
      temp: '82',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 9,
    },
    {
      temp: '79',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 10,
    },
    {
      temp: '77',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 10,
    },
    {
      temp: '75',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 10,
    },
    {
      temp: '73',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 10,
    },
    {
      temp: '72',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 10,
    },
    {
      temp: '70',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 10,
    },
    {
      temp: '71',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 AM',
      hour: 6,
      day: 10,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 AM',
      hour: 7,
      day: 10,
    },
    {
      temp: '82',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 AM',
      hour: 8,
      day: 10,
    },
    {
      temp: '85',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 AM',
      hour: 9,
      day: 10,
    },
    {
      temp: '89',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 AM',
      hour: 10,
      day: 10,
    },
    {
      temp: '92',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 AM',
      hour: 11,
      day: 10,
    },
    {
      temp: '94',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 PM',
      hour: 12,
      day: 10,
    },
    {
      temp: '97',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 PM',
      hour: 13,
      day: 10,
    },
    {
      temp: '99',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 PM',
      hour: 14,
      day: 10,
    },
    {
      temp: '100',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 PM',
      hour: 15,
      day: 10,
    },
    {
      temp: '100',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 PM',
      hour: 16,
      day: 10,
    },
    {
      temp: '99',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 PM',
      hour: 17,
      day: 10,
    },
    {
      temp: '97',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 PM',
      hour: 18,
      day: 10,
    },
    {
      temp: '94',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 10,
    },
    {
      temp: '90',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 10,
    },
    {
      temp: '86',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 10,
    },
    {
      temp: '83',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 10,
    },
    {
      temp: '81',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 10,
    },
    {
      temp: '78',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 11,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 11,
    },
    {
      temp: '75',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 11,
    },
    {
      temp: '73',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 11,
    },
    {
      temp: '71',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 11,
    },
    {
      temp: '71',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 11,
    },
    {
      temp: '71',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 AM',
      hour: 6,
      day: 11,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 AM',
      hour: 7,
      day: 11,
    },
    {
      temp: '80',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 AM',
      hour: 8,
      day: 11,
    },
    {
      temp: '84',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 AM',
      hour: 9,
      day: 11,
    },
    {
      temp: '88',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 AM',
      hour: 10,
      day: 11,
    },
    {
      temp: '91',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 AM',
      hour: 11,
      day: 11,
    },
    {
      temp: '93',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 PM',
      hour: 12,
      day: 11,
    },
    {
      temp: '95',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 PM',
      hour: 13,
      day: 11,
    },
    {
      temp: '97',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 PM',
      hour: 14,
      day: 11,
    },
    {
      temp: '98',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 PM',
      hour: 15,
      day: 11,
    },
    {
      temp: '98',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 PM',
      hour: 16,
      day: 11,
    },
    {
      temp: '97',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 PM',
      hour: 17,
      day: 11,
    },
    {
      temp: '95',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 PM',
      hour: 18,
      day: 11,
    },
    {
      temp: '92',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 11,
    },
    {
      temp: '88',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 11,
    },
    {
      temp: '85',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 11,
    },
    {
      temp: '82',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 11,
    },
    {
      temp: '79',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 11,
    },
    {
      temp: '77',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 12,
    },
    {
      temp: '75',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 12,
    },
    {
      temp: '73',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 12,
    },
    {
      temp: '72',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 12,
    },
    {
      temp: '70',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 12,
    },
    {
      temp: '69',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 12,
    },
    {
      temp: '69',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 AM',
      hour: 6,
      day: 12,
    },
    {
      temp: '74',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 AM',
      hour: 7,
      day: 12,
    },
    {
      temp: '79',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 AM',
      hour: 8,
      day: 12,
    },
    {
      temp: '83',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 AM',
      hour: 9,
      day: 12,
    },
    {
      temp: '86',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 AM',
      hour: 10,
      day: 12,
    },
    {
      temp: '90',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 AM',
      hour: 11,
      day: 12,
    },
    {
      temp: '92',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 PM',
      hour: 12,
      day: 12,
    },
    {
      temp: '94',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 PM',
      hour: 13,
      day: 12,
    },
    {
      temp: '96',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 PM',
      hour: 14,
      day: 12,
    },
    {
      temp: '96',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 PM',
      hour: 15,
      day: 12,
    },
    {
      temp: '96',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 PM',
      hour: 16,
      day: 12,
    },
    {
      temp: '95',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 PM',
      hour: 17,
      day: 12,
    },
    {
      temp: '94',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 PM',
      hour: 18,
      day: 12,
    },
    {
      temp: '92',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 12,
    },
    {
      temp: '88',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 12,
    },
    {
      temp: '85',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 12,
    },
    {
      temp: '83',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 12,
    },
    {
      temp: '80',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 12,
    },
    {
      temp: '77',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 13,
    },
    {
      temp: '75',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 13,
    },
    {
      temp: '73',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 13,
    },
    {
      temp: '71',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 13,
    },
    {
      temp: '70',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 13,
    },
    {
      temp: '69',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 13,
    },
    {
      temp: '69',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 AM',
      hour: 6,
      day: 13,
    },
    {
      temp: '74',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 AM',
      hour: 7,
      day: 13,
    },
    {
      temp: '79',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 AM',
      hour: 8,
      day: 13,
    },
    {
      temp: '84',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 AM',
      hour: 9,
      day: 13,
    },
    {
      temp: '87',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 AM',
      hour: 10,
      day: 13,
    },
    {
      temp: '91',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 AM',
      hour: 11,
      day: 13,
    },
    {
      temp: '93',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 PM',
      hour: 12,
      day: 13,
    },
    {
      temp: '96',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 PM',
      hour: 13,
      day: 13,
    },
    {
      temp: '98',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 PM',
      hour: 14,
      day: 13,
    },
    {
      temp: '99',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 PM',
      hour: 15,
      day: 13,
    },
    {
      temp: '99',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 PM',
      hour: 16,
      day: 13,
    },
    {
      temp: '99',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 PM',
      hour: 17,
      day: 13,
    },
    {
      temp: '98',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 PM',
      hour: 18,
      day: 13,
    },
    {
      temp: '95',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 13,
    },
    {
      temp: '91',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 13,
    },
    {
      temp: '88',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 13,
    },
    {
      temp: '85',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 13,
    },
    {
      temp: '82',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 13,
    },
    {
      temp: '79',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 14,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 14,
    },
    {
      temp: '74',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 14,
    },
    {
      temp: '72',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 14,
    },
    {
      temp: '71',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 14,
    },
    {
      temp: '70',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 14,
    },
    {
      temp: '71',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 AM',
      hour: 6,
      day: 14,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 AM',
      hour: 7,
      day: 14,
    },
    {
      temp: '82',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 AM',
      hour: 8,
      day: 14,
    },
    {
      temp: '87',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 AM',
      hour: 9,
      day: 14,
    },
    {
      temp: '91',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 AM',
      hour: 10,
      day: 14,
    },
    {
      temp: '94',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 AM',
      hour: 11,
      day: 14,
    },
    {
      temp: '97',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 PM',
      hour: 12,
      day: 14,
    },
    {
      temp: '100',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 PM',
      hour: 13,
      day: 14,
    },
    {
      temp: '101',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 PM',
      hour: 14,
      day: 14,
    },
    {
      temp: '102',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 PM',
      hour: 15,
      day: 14,
    },
    {
      temp: '102',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 PM',
      hour: 16,
      day: 14,
    },
    {
      temp: '102',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 PM',
      hour: 17,
      day: 14,
    },
    {
      temp: '100',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 PM',
      hour: 18,
      day: 14,
    },
    {
      temp: '97',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 PM',
      hour: 19,
      day: 14,
    },
    {
      temp: '93',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 PM',
      hour: 20,
      day: 14,
    },
    {
      temp: '90',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 PM',
      hour: 21,
      day: 14,
    },
    {
      temp: '87',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 PM',
      hour: 22,
      day: 14,
    },
    {
      temp: '84',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 PM',
      hour: 23,
      day: 14,
    },
    {
      temp: '81',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 AM',
      hour: 0,
      day: 15,
    },
    {
      temp: '78',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 AM',
      hour: 1,
      day: 15,
    },
    {
      temp: '76',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 AM',
      hour: 2,
      day: 15,
    },
    {
      temp: '74',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 AM',
      hour: 3,
      day: 15,
    },
    {
      temp: '73',
      icon: 'clear',
      condition: 'Clear',
      time: '4:00 AM',
      hour: 4,
      day: 15,
    },
    {
      temp: '72',
      icon: 'clear',
      condition: 'Clear',
      time: '5:00 AM',
      hour: 5,
      day: 15,
    },
    {
      temp: '73',
      icon: 'clear',
      condition: 'Clear',
      time: '6:00 AM',
      hour: 6,
      day: 15,
    },
    {
      temp: '78',
      icon: 'clear',
      condition: 'Clear',
      time: '7:00 AM',
      hour: 7,
      day: 15,
    },
    {
      temp: '84',
      icon: 'clear',
      condition: 'Clear',
      time: '8:00 AM',
      hour: 8,
      day: 15,
    },
    {
      temp: '89',
      icon: 'clear',
      condition: 'Clear',
      time: '9:00 AM',
      hour: 9,
      day: 15,
    },
    {
      temp: '93',
      icon: 'clear',
      condition: 'Clear',
      time: '10:00 AM',
      hour: 10,
      day: 15,
    },
    {
      temp: '96',
      icon: 'clear',
      condition: 'Clear',
      time: '11:00 AM',
      hour: 11,
      day: 15,
    },
    {
      temp: '99',
      icon: 'clear',
      condition: 'Clear',
      time: '12:00 PM',
      hour: 12,
      day: 15,
    },
    {
      temp: '102',
      icon: 'clear',
      condition: 'Clear',
      time: '1:00 PM',
      hour: 13,
      day: 15,
    },
    {
      temp: '103',
      icon: 'clear',
      condition: 'Clear',
      time: '2:00 PM',
      hour: 14,
      day: 15,
    },
    {
      temp: '104',
      icon: 'clear',
      condition: 'Clear',
      time: '3:00 PM',
      hour: 15,
      day: 15,
    },
  ],
};

export default cityData;
