const weatherIcons = {
  chanceflurries: 'snow',
  chancerain: 'rain-chance',
  chancesleet: 'sleet-chance',
  chancesnow: 'snow',
  chancetstorms: 'tstorm-chance',
  clear: 'clear',
  cloudy: 'cloudy',
  flurries: 'snow',
  hazy: 'haze-fog',
  haze: 'haze-fog',
  fog: 'haze-fog',
  mostlycloudy: 'cloudy-mostly',
  mostlysunny: 'cloudy-partly',
  partlycloudy: 'cloudy-partly',
  partlysunny: 'cloudy-partly',
  rain: 'rain',
  sleet: 'sleet',
  snow: 'snow',
  sunny: 'clear',
  tstorms: 'tstorm',
  nt_chanceflurries: 'snow',
  nt_chancerain: 'rain-chance',
  nt_chancesleet: 'sleet-chance',
  nt_chancesnow: 'snow',
  nt_chancetstorms: 'tstorm-chance',
  nt_clear: 'clear-night',
  nt_cloudy: 'cloudy',
  nt_flurries: 'snow',
  nt_hazy: 'haze-fog',
  nt_fog: 'haze-fog',
  nt_mostlycloudy: 'cloudy-mostly-night',
  nt_mostlysunny: 'cloudy-partly-night',
  nt_partlycloudy: 'cloudy-partly-night',
  nt_partlysunny: 'cloudy-partly-night',
  nt_rain: 'rain',
  nt_sleet: 'sleet',
  nt_snow: 'snow',
  nt_sunny: 'clear',
  nt_tstorms: 'tstorm',
  unknown: 'undefined',
  undefined: 'undefined',
};

export default weatherIcons;
